name: Deploy Release Automated Build

env:
  DOCKERHUB_REPO: flyskype2021/focalboard

# Trigger on release
on:
  repository_dispatch:
    types: [focalboard]
    branches: [master]
    client_payload:
      release_version:
        description: "release focalboard version"
        required: true
        
jobs:
  build:

    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker image labels
        uses: crazy-max/ghaction-docker-meta@v2.5.0
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          label-custom: |
            maintainer=flyskype2021
            org.opencontainers.image.title=focalboard
            org.opencontainers.image.description=Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.
            org.opencontainers.image.url=https://www.focalboard.com
            org.opencontainers.image.licenses=Mattermost Licensing
            org.opencontainers.image.version=${{github.event.client_payload.release_version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          pull: true
          push: true
          build-args: FOCALBOARD_REF=v${{github.event.client_payload.release_version}}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{github.event.client_payload.release_version}}
            ${{ env.DOCKERHUB_REPO }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
