name: build

env:
  DOCKERHUB_REPO: nicoulaj/focalboard
  FOCALBOARD_MAJOR: 0
  FOCALBOARD_MINOR: 6
  FOCALBOARD_INCREMENT: 1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform: [ 'linux/amd64', 'linux/arm/v6', 'linux/arm/v7' ]
        include:
          - platform: linux/amd64
            platform_tag_name: linux-amd64
            goarch: amd64
          - platform: linux/386
            platform_tag_name: linux-386
            goarch: 386
          - platform: linux/arm/v6
            platform_tag_name: linux-arm-v6
            goarch: arm
          - platform: linux/arm/v7
            platform_tag_name: linux-arm-v7
            goarch: arm
          - platform: linux/arm64/v8
            platform_tag_name: linux-arm64-v8
            goarch: arm64
          - platform: linux/mips64le
            platform_tag_name: linux-mips64le
            goarch: mips64le
          - platform: linux/ppc64le
            platform_tag_name: linux-ppc64le
            goarch: ppc64le
          - platform: linux/s390x
            platform_tag_name: linux-s390x
            goarch: s390x

    name: ${{ matrix.platform }}

    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker image labels
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKERHUB_REPO }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            FOCALBOARD_MAJOR=${{ env.FOCALBOARD_MAJOR }}
            FOCALBOARD_MINOR=${{ env.FOCALBOARD_MINOR }}
            FOCALBOARD_INCREMENT=${{ env.FOCALBOARD_INCREMENT }}
            GOARCH=${{ matrix.goarch }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}.${{ env.FOCALBOARD_INCREMENT }}-${{ matrix.platform_tag_name }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}.${{ env.FOCALBOARD_MINOR }}-${{ matrix.platform_tag_name }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}-${{ matrix.platform_tag_name }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.FOCALBOARD_MAJOR }}
            ${{ env.DOCKERHUB_REPO }}:${{ matrix.platform_tag_name }}
            ${{ env.DOCKERHUB_REPO }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
